/*
 * crypt.c — crypt(3) for NanOS, SHA-512 scheme ($6$), glibc/Drepper-compatible.
 *
 * picolibc declares no crypt(); Dropbear (and any password-auth caller) needs it. This is a
 * self-contained, spec-exact implementation: a SHA-512 core (FIPS 180-4) plus Ulrich Drepper's
 * sha512-crypt key-stretching. The output matches `openssl passwd -6` / glibc byte-for-byte, so a
 * hash generated by either verifies here. Only the $6$ scheme is implemented (the Linux default);
 * a hash with any other/none prefix returns NULL (unsupported), never a wrong match.
 */
#include <string.h>
#include <stdint.h>
#include <stddef.h>

/* ---- SHA-512 (FIPS 180-4) ---------------------------------------------------------------- */
typedef struct { uint64_t h[8]; uint64_t len; unsigned char buf[128]; unsigned idx; } SHA512;

static const uint64_t K512[80] = {
	0x428a2f98d728ae22ULL,0x7137449123ef65cdULL,0xb5c0fbcfec4d3b2fULL,0xe9b5dba58189dbbcULL,
	0x3956c25bf348b538ULL,0x59f111f1b605d019ULL,0x923f82a4af194f9bULL,0xab1c5ed5da6d8118ULL,
	0xd807aa98a3030242ULL,0x12835b0145706fbeULL,0x243185be4ee4b28cULL,0x550c7dc3d5ffb4e2ULL,
	0x72be5d74f27b896fULL,0x80deb1fe3b1696b1ULL,0x9bdc06a725c71235ULL,0xc19bf174cf692694ULL,
	0xe49b69c19ef14ad2ULL,0xefbe4786384f25e3ULL,0x0fc19dc68b8cd5b5ULL,0x240ca1cc77ac9c65ULL,
	0x2de92c6f592b0275ULL,0x4a7484aa6ea6e483ULL,0x5cb0a9dcbd41fbd4ULL,0x76f988da831153b5ULL,
	0x983e5152ee66dfabULL,0xa831c66d2db43210ULL,0xb00327c898fb213fULL,0xbf597fc7beef0ee4ULL,
	0xc6e00bf33da88fc2ULL,0xd5a79147930aa725ULL,0x06ca6351e003826fULL,0x142929670a0e6e70ULL,
	0x27b70a8546d22ffcULL,0x2e1b21385c26c926ULL,0x4d2c6dfc5ac42aedULL,0x53380d139d95b3dfULL,
	0x650a73548baf63deULL,0x766a0abb3c77b2a8ULL,0x81c2c92e47edaee6ULL,0x92722c851482353bULL,
	0xa2bfe8a14cf10364ULL,0xa81a664bbc423001ULL,0xc24b8b70d0f89791ULL,0xc76c51a30654be30ULL,
	0xd192e819d6ef5218ULL,0xd69906245565a910ULL,0xf40e35855771202aULL,0x106aa07032bbd1b8ULL,
	0x19a4c116b8d2d0c8ULL,0x1e376c085141ab53ULL,0x2748774cdf8eeb99ULL,0x34b0bcb5e19b48a8ULL,
	0x391c0cb3c5c95a63ULL,0x4ed8aa4ae3418acbULL,0x5b9cca4f7763e373ULL,0x682e6ff3d6b2b8a3ULL,
	0x748f82ee5defb2fcULL,0x78a5636f43172f60ULL,0x84c87814a1f0ab72ULL,0x8cc702081a6439ecULL,
	0x90befffa23631e28ULL,0xa4506cebde82bde9ULL,0xbef9a3f7b2c67915ULL,0xc67178f2e372532bULL,
	0xca273eceea26619cULL,0xd186b8c721c0c207ULL,0xeada7dd6cde0eb1eULL,0xf57d4f7fee6ed178ULL,
	0x06f067aa72176fbaULL,0x0a637dc5a2c898a6ULL,0x113f9804bef90daeULL,0x1b710b35131c471bULL,
	0x28db77f523047d84ULL,0x32caab7b40c72493ULL,0x3c9ebe0a15c9bebcULL,0x431d67c49c100d4cULL,
	0x4cc5d4becb3e42b6ULL,0x597f299cfc657e2aULL,0x5fcb6fab3ad6faecULL,0x6c44198c4a475817ULL,
};

#define ROR64(x,n) (((x) >> (n)) | ((x) << (64 - (n))))

static void sha512_init(SHA512* s) {
	s->h[0]=0x6a09e667f3bcc908ULL; s->h[1]=0xbb67ae8584caa73bULL;
	s->h[2]=0x3c6ef372fe94f82bULL; s->h[3]=0xa54ff53a5f1d36f1ULL;
	s->h[4]=0x510e527fade682d1ULL; s->h[5]=0x9b05688c2b3e6c1fULL;
	s->h[6]=0x1f83d9abfb41bd6bULL; s->h[7]=0x5be0cd19137e2179ULL;
	s->len = 0; s->idx = 0;
}

static void sha512_block(SHA512* s, const unsigned char* p) {
	uint64_t w[80];
	for (int i = 0; i < 16; i++)
		w[i] = ((uint64_t)p[i*8]<<56)|((uint64_t)p[i*8+1]<<48)|((uint64_t)p[i*8+2]<<40)
		     | ((uint64_t)p[i*8+3]<<32)|((uint64_t)p[i*8+4]<<24)|((uint64_t)p[i*8+5]<<16)
		     | ((uint64_t)p[i*8+6]<<8)|((uint64_t)p[i*8+7]);
	for (int i = 16; i < 80; i++) {
		uint64_t s0 = ROR64(w[i-15],1) ^ ROR64(w[i-15],8) ^ (w[i-15]>>7);
		uint64_t s1 = ROR64(w[i-2],19) ^ ROR64(w[i-2],61) ^ (w[i-2]>>6);
		w[i] = w[i-16] + s0 + w[i-7] + s1;
	}
	uint64_t a=s->h[0],b=s->h[1],c=s->h[2],d=s->h[3],e=s->h[4],f=s->h[5],g=s->h[6],h=s->h[7];
	for (int i = 0; i < 80; i++) {
		uint64_t S1 = ROR64(e,14) ^ ROR64(e,18) ^ ROR64(e,41);
		uint64_t ch = (e & f) ^ (~e & g);
		uint64_t t1 = h + S1 + ch + K512[i] + w[i];
		uint64_t S0 = ROR64(a,28) ^ ROR64(a,34) ^ ROR64(a,39);
		uint64_t maj = (a & b) ^ (a & c) ^ (b & c);
		uint64_t t2 = S0 + maj;
		h=g; g=f; f=e; e=d+t1; d=c; c=b; b=a; a=t1+t2;
	}
	s->h[0]+=a; s->h[1]+=b; s->h[2]+=c; s->h[3]+=d;
	s->h[4]+=e; s->h[5]+=f; s->h[6]+=g; s->h[7]+=h;
}

static void sha512_update(SHA512* s, const void* data, size_t n) {
	const unsigned char* p = (const unsigned char*) data;
	s->len += n;
	while (n) {
		unsigned take = 128 - s->idx;
		if (take > n) take = (unsigned) n;
		memcpy(s->buf + s->idx, p, take);
		s->idx += take; p += take; n -= take;
		if (s->idx == 128) { sha512_block(s, s->buf); s->idx = 0; }
	}
}

static void sha512_final(SHA512* s, unsigned char out[64]) {
	uint64_t bits = s->len * 8;
	unsigned char pad = 0x80;
	sha512_update(s, &pad, 1);
	unsigned char z = 0;
	while (s->idx != 112) sha512_update(s, &z, 1);
	unsigned char lenb[16];
	for (int i = 0; i < 8; i++) lenb[i] = 0;            // high 64 bits of the 128-bit length = 0
	for (int i = 0; i < 8; i++) lenb[15-i] = (unsigned char)(bits >> (i*8));
	sha512_update(s, lenb, 16);
	for (int i = 0; i < 8; i++) {
		out[i*8+0]=(unsigned char)(s->h[i]>>56); out[i*8+1]=(unsigned char)(s->h[i]>>48);
		out[i*8+2]=(unsigned char)(s->h[i]>>40); out[i*8+3]=(unsigned char)(s->h[i]>>32);
		out[i*8+4]=(unsigned char)(s->h[i]>>24); out[i*8+5]=(unsigned char)(s->h[i]>>16);
		out[i*8+6]=(unsigned char)(s->h[i]>>8);  out[i*8+7]=(unsigned char)(s->h[i]);
	}
}

/* ---- sha512-crypt ($6$), per Ulrich Drepper's specification ------------------------------ */
static const char b64[] = "./0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz";

/* Append the custom base64 of (a,b,c) — three bytes -> four chars, little-endian groups as the
 * spec orders them. n = number of chars to emit (handles the final short group). */
static char* b64_from_24(char* p, unsigned a, unsigned b, unsigned c, int n) {
	unsigned w = (a << 16) | (b << 8) | c;
	while (n-- > 0) { *p++ = b64[w & 0x3f]; w >>= 6; }
	return p;
}

int crypt_r_sha512(const char* key, const char* setting, char* out, size_t outlen);

/* The public crypt(): a static buffer (classic contract — valid until the next call). C linkage
 * so the symbol is `crypt` under both the C target build and the g++ host-test build. */
static char g_crypt_out[128];

#ifdef __cplusplus
extern "C"
#endif
char* crypt(const char* key, const char* setting) {
	if (!setting || setting[0] != '$' || setting[1] != '6' || setting[2] != '$')
		return 0;   /* only $6$ supported */
	if (crypt_r_sha512(key, setting, g_crypt_out, sizeof g_crypt_out) != 0)
		return 0;
	return g_crypt_out;
}

int crypt_r_sha512(const char* key, const char* setting, char* out, size_t outlen) {
	/* Parse the salt: after "$6$", an optional "rounds=N$", then up to 16 salt chars up to '$'. */
	const char* sp = setting + 3;
	unsigned long rounds = 5000;
	int rounds_custom = 0;
	if (strncmp(sp, "rounds=", 7) == 0) {
		const char* r = sp + 7;
		unsigned long v = 0;
		while (*r >= '0' && *r <= '9') { v = v*10 + (unsigned)(*r - '0'); r++; }
		if (*r == '$') {
			if (v < 1000) v = 1000;
			if (v > 999999999UL) v = 999999999UL;
			rounds = v; rounds_custom = 1; sp = r + 1;
		}
	}
	char salt[17];
	int saltlen = 0;
	while (sp[saltlen] && sp[saltlen] != '$' && saltlen < 16) { salt[saltlen] = sp[saltlen]; saltlen++; }
	salt[saltlen] = 0;

	size_t keylen = strlen(key);
	unsigned char A[64], B[64], DP[64], DS[64];
	SHA512 ctx, alt;

	/* digest B = SHA512(key + salt + key) */
	sha512_init(&alt);
	sha512_update(&alt, key, keylen);
	sha512_update(&alt, salt, (size_t) saltlen);
	sha512_update(&alt, key, keylen);
	sha512_final(&alt, B);

	/* digest A */
	sha512_init(&ctx);
	sha512_update(&ctx, key, keylen);
	sha512_update(&ctx, salt, (size_t) saltlen);
	for (size_t i = keylen; i > 64; i -= 64) sha512_update(&ctx, B, 64);
	sha512_update(&ctx, B, keylen % 64 ? keylen % 64 : (keylen ? 64 : 0));
	for (size_t i = keylen; i > 0; i >>= 1)
		if (i & 1) sha512_update(&ctx, B, 64); else sha512_update(&ctx, key, keylen);
	sha512_final(&ctx, A);

	/* DP = SHA512(key keylen times) -> P sequence of length keylen */
	sha512_init(&ctx);
	for (size_t i = 0; i < keylen; i++) sha512_update(&ctx, key, keylen);
	sha512_final(&ctx, DP);
	unsigned char Pbuf[256], Sbuf[256];
	{ size_t c = 0; while (c + 64 <= keylen) { memcpy(Pbuf + c, DP, 64); c += 64; } if (c < keylen) memcpy(Pbuf + c, DP, keylen - c); }

	/* DS = SHA512(salt, 16 + A[0] times) -> S sequence of length saltlen */
	sha512_init(&ctx);
	for (int i = 0; i < 16 + (int) A[0]; i++) sha512_update(&ctx, salt, (size_t) saltlen);
	sha512_final(&ctx, DS);
	{ size_t c = 0; while (c + 64 <= (size_t) saltlen) { memcpy(Sbuf + c, DS, 64); c += 64; } if (c < (size_t) saltlen) memcpy(Sbuf + c, DS, (size_t) saltlen - c); }

	/* The big loop. */
	unsigned char C[64];
	memcpy(C, A, 64);
	for (unsigned long r = 0; r < rounds; r++) {
		sha512_init(&ctx);
		if (r & 1) sha512_update(&ctx, Pbuf, keylen); else sha512_update(&ctx, C, 64);
		if (r % 3) sha512_update(&ctx, Sbuf, (size_t) saltlen);
		if (r % 7) sha512_update(&ctx, Pbuf, keylen);
		if (r & 1) sha512_update(&ctx, C, 64); else sha512_update(&ctx, Pbuf, keylen);
		sha512_final(&ctx, C);
	}

	/* Build the output: "$6$" [rounds=N$] salt "$" + base64(C in the spec's permuted order). */
	char* o = out;
	const char* hdr = "$6$";
	for (int i = 0; hdr[i]; i++) *o++ = hdr[i];
	if (rounds_custom) {
		const char* pre = "rounds=";
		for (int i = 0; pre[i]; i++) *o++ = pre[i];
		char num[16]; int nl = 0; unsigned long v = rounds;
		char tmp[16]; int t = 0; do { tmp[t++] = (char)('0' + v % 10); v /= 10; } while (v);
		while (t) num[nl++] = tmp[--t];
		for (int i = 0; i < nl; i++) *o++ = num[i];
		*o++ = '$';
	}
	for (int i = 0; i < saltlen; i++) *o++ = salt[i];
	*o++ = '$';
	/* The fixed SHA-512 byte permutation for the output encoding (glibc sha512-crypt): 21 groups
	 * of 3 bytes -> 4 chars each, then a final group of 1 byte -> 2 chars. */
	static const int perm[21][3] = {
		{0,21,42},{22,43,1},{44,2,23},{3,24,45},{25,46,4},{47,5,26},{6,27,48},
		{28,49,7},{50,8,29},{9,30,51},{31,52,10},{53,11,32},{12,33,54},{34,55,13},
		{56,14,35},{15,36,57},{37,58,16},{59,17,38},{18,39,60},{40,61,19},{62,20,41},
	};
	for (int g = 0; g < 21; g++)
		o = b64_from_24(o, C[perm[g][0]], C[perm[g][1]], C[perm[g][2]], 4);
	o = b64_from_24(o, 0, 0, C[63], 2);   /* final group: byte 63 -> 2 chars */
	*o = 0;
	(void) outlen;
	return 0;
}
