/*
 * mknx — turn a linked i686 ELF (built with `ld --emit-relocs`) into a NanOS module
 * (.nxe executable or .ndl shared library). Replaces `objcopy -O binary`: besides the
 * flat load image it also emits the base-relocation table (R_386_32 fixup sites), the
 * export table (named symbols a .ndl provides), the import table (from a .nximports
 * section), and the needed-library list — so modules can load at any base and resolve
 * imports/exports by name (the Windows-PE model). See kernel/NxFormat.h.
 *
 * Build-host tool (native cc); parses ELF32 by hand (no libelf dependency).
 *
 * Usage:
 *   mknx <in.elf> <out.nxe|out.ndl> [--dll] [--export NAME]... [--export-all]
 *        [--need NAME]...
 *   mknx <in.elf> <out.s> --implib [--export NAME]... [--export-all]
 *
 * Imports are derived from the linked symbols named "__imp_<name>": each is an IAT slot
 * the loader fills with the address of import "<name>" (the import library — generated by
 * --implib — provides the slot + a `<name>: jmp [__imp_<name>]` thunk). --implib reads a
 * library ELF and writes that import library (a thunk + slot per exported function).
 */
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <stdint.h>

#include "NxFormat.h"   /* compiled with -Ikernel */

/* ---- minimal ELF, width selected by -DNX_FORCE64 ----
 * Under -DNX_FORCE64 (the mknx64 build) we parse ELF64 and the x86_64 relocation types;
 * without it we parse the historical ELF32 / R_386_* (i686). The generic `Elf_*` names and
 * `R_*` / `EM_TARGET` / `ELF_R_*` macros below let the body stay identical across both. */
#if defined(NX_FORCE64)
typedef struct { unsigned char e_ident[16]; uint16_t e_type, e_machine; uint32_t e_version;
	uint64_t e_entry, e_phoff, e_shoff; uint32_t e_flags; uint16_t e_ehsize, e_phentsize,
	e_phnum, e_shentsize, e_shnum, e_shstrndx; } Elf_Ehdr;
typedef struct { uint32_t sh_name, sh_type; uint64_t sh_flags, sh_addr, sh_offset, sh_size;
	uint32_t sh_link, sh_info; uint64_t sh_addralign, sh_entsize; } Elf_Shdr;
typedef struct { uint32_t st_name; unsigned char st_info, st_other; uint16_t st_shndx;
	uint64_t st_value, st_size; } Elf_Sym;
typedef struct { uint64_t r_offset, r_info; } Elf_Rel;             /* SHT_REL  (no addend) */
typedef struct { uint64_t r_offset, r_info, r_addend; } Elf_Rela; /* SHT_RELA (with addend) */
#define SHT_RELA_T   4
#define R_ABS64      1     /* R_X86_64_64  — 8-byte absolute: a base-reloc site */
#define R_PC32       2     /* R_X86_64_PC32 — RIP-relative: NOT relocated (position-indep.) */
#define R_ABS32S     11    /* R_X86_64_32S — forces image into low 2 GiB; never a base-reloc */
#define EM_TARGET    62    /* EM_X86_64 */
#define ELF_R_TYPE(i) ((uint32_t)((i) & 0xffffffff))
#define ELF_R_SYM(i)  ((uint32_t)((i) >> 32))
#define ELF_ST_BIND(i) ((i) >> 4)
#else
typedef struct { unsigned char e_ident[16]; uint16_t e_type, e_machine; uint32_t e_version,
	e_entry, e_phoff, e_shoff, e_flags; uint16_t e_ehsize, e_phentsize, e_phnum,
	e_shentsize, e_shnum, e_shstrndx; } Elf_Ehdr;
typedef struct { uint32_t sh_name, sh_type, sh_flags, sh_addr, sh_offset, sh_size,
	sh_link, sh_info, sh_addralign, sh_entsize; } Elf_Shdr;
typedef struct { uint32_t st_name, st_value, st_size; unsigned char st_info, st_other;
	uint16_t st_shndx; } Elf_Sym;
typedef struct { uint32_t r_offset, r_info; } Elf_Rel;
#define R_ABS64      1     /* R_386_32 */
#define R_PC32       2     /* R_386_PC32 */
#define EM_TARGET    3     /* EM_386 */
#define ELF_R_TYPE(i) ((i) & 0xff)
#define ELF_R_SYM(i)  ((i) >> 8)
#define ELF_ST_BIND(i) ((i) >> 4)
#endif
#define SHT_PROGBITS 1
#define SHT_SYMTAB   2
#define SHT_STRTAB   3
#define SHT_REL      9
#define SHT_NOBITS   8
#define SHF_ALLOC    2
#define SHF_EXECINSTR 4
#define STB_GLOBAL   1
#define STB_WEAK     2
#define SHN_UNDEF    0
#define SHN_ABS      0xfff1

static unsigned char* g_elf;
static long g_elfLen;
static Elf_Ehdr* g_eh;
static Elf_Shdr* g_sh;     /* section headers */
static int g_nsh;

static void die(const char* m) { fprintf(stderr, "mknx: %s\n", m); exit(1); }

static Elf_Shdr* sh(int i) { return &g_sh[i]; }

/* Section flags of a defined symbol's section, or 0 if undefined/special (ABS/COMMON).
 * Used to classify symbols by their section rather than st_type, since picolibc's
 * assembly routines (memcpy/strlen/...) are global but STT_NOTYPE. */
static unsigned symSecFlags(Elf_Sym* s) {
	if (s->st_shndx == 0 || s->st_shndx >= g_nsh) return 0;
	return g_sh[s->st_shndx].sh_flags;
}
static const char* shname(Elf_Shdr* s) {
	Elf_Shdr* str = sh(g_eh->e_shstrndx);
	return (const char*) (g_elf + str->sh_offset + s->sh_name);
}

/* Growable byte buffer. */
typedef struct { unsigned char* p; unsigned len, cap; } Buf;
static void bput(Buf* b, const void* d, unsigned n) {
	if (b->len + n > b->cap) { b->cap = (b->len + n) * 2 + 64; b->p = realloc(b->p, b->cap); }
	memcpy(b->p + b->len, d, n); b->len += n;
}
/* Append a machine-width address (4 bytes on i386, 8 on x86_64): used for the reloc table,
 * whose entries are NxReloc { nxaddr_t off }. */
static nxaddr_t bu64(Buf* b, nxaddr_t v) { unsigned o = b->len; bput(b, &v, sizeof v); return o; }

/* Add `lib` to the needed-library list unless already present (by name). The list is small
 * (one entry per distinct import library, typically just "libc.ndl"), so a linear scan is fine. */
static void addNeed(char** needs, int* nNeeds, const char* lib) {
	for (int i = 0; i < *nNeeds; i++)
		if (!strcmp(needs[i], lib)) return;
	if (*nNeeds >= 64) die("too many needed libraries (max 64)");
	needs[(*nNeeds)++] = (char*) lib;
}

int main(int argc, char** argv) {
	const char* in = 0; const char* out = 0;
	int isDll = 0, exportAll = 0, implib = 0;
	const char* soname = 0;          /* --implib: source library the thunks bind to */
	char* wantExport[512]; int nWantExport = 0;
	char* needs[64]; int nNeeds = 0;
	for (int i = 1; i < argc; i++) {
		if (!strcmp(argv[i], "--dll")) isDll = 1;
		else if (!strcmp(argv[i], "--implib")) implib = 1;
		else if (!strcmp(argv[i], "--soname") && i + 1 < argc) soname = argv[++i];
		else if (!strcmp(argv[i], "--export-all")) exportAll = 1;
		else if (!strcmp(argv[i], "--export") && i + 1 < argc) wantExport[nWantExport++] = argv[++i];
		else if (!strcmp(argv[i], "--need") && i + 1 < argc) needs[nNeeds++] = argv[++i];
		else if (!in) in = argv[i];
		else if (!out) out = argv[i];
	}
	if (!in || !out) die("usage: mknx <in.elf> <out> [--dll] [--export N|--export-all] [--need N]");

	/* Read the whole ELF. */
	FILE* f = fopen(in, "rb");
	if (!f) die("cannot open input");
	fseek(f, 0, SEEK_END); g_elfLen = ftell(f); fseek(f, 0, SEEK_SET);
	g_elf = malloc(g_elfLen);
	if (fread(g_elf, 1, g_elfLen, f) != (size_t) g_elfLen) die("short read");
	fclose(f);

	g_eh = (Elf_Ehdr*) g_elf;
	if (memcmp(g_eh->e_ident, "\177ELF", 4) != 0) die("not an ELF");
	if (g_eh->e_machine != EM_TARGET) die("wrong machine (expected EM_TARGET)");
	g_sh = (Elf_Shdr*) (g_elf + g_eh->e_shoff);
	g_nsh = g_eh->e_shnum;

	/* 1) Image extent: loadBase = min SHF_ALLOC vaddr; bssStart = end of allocated
	 *    PROGBITS; bssEnd = end of all allocated sections (incl NOBITS .bss). */
	nxaddr_t loadBase = (nxaddr_t) -1, bssStart = 0, bssEnd = 0;
	for (int i = 0; i < g_nsh; i++) {
		Elf_Shdr* s = sh(i);
		if (!(s->sh_flags & SHF_ALLOC) || s->sh_size == 0) continue;
		if (s->sh_addr < loadBase) loadBase = s->sh_addr;
		nxaddr_t end = s->sh_addr + s->sh_size;
		if (end > bssEnd) bssEnd = end;
		if (s->sh_type != SHT_NOBITS && end > bssStart) bssStart = end;
	}
	if (loadBase == (nxaddr_t) -1) die("no allocatable sections");
	nxaddr_t imageSize = bssStart - loadBase;

	/* Flat load image [loadBase, bssStart): copy each allocated PROGBITS section. */
	unsigned char* image = calloc(1, imageSize);
	for (int i = 0; i < g_nsh; i++) {
		Elf_Shdr* s = sh(i);
		if ((s->sh_flags & SHF_ALLOC) && s->sh_type == SHT_PROGBITS && s->sh_size)
			memcpy(image + (s->sh_addr - loadBase), g_elf + s->sh_offset, s->sh_size);
	}

	/* Locate symtab + its strtab (for exports). */
	Elf_Sym* sym = 0; int nsym = 0; const char* symstr = 0;
	for (int i = 0; i < g_nsh; i++)
		if (sh(i)->sh_type == SHT_SYMTAB) {
			sym = (Elf_Sym*) (g_elf + sh(i)->sh_offset);
			nsym = sh(i)->sh_size / sizeof(Elf_Sym);
			symstr = (const char*) (g_elf + sh(sh(i)->sh_link)->sh_offset);
		}

	/* --implib: write an import library (.s) — one `name: jmp [__imp_name]` thunk + an
	 * `__imp_name` IAT slot per exported FUNC. A program links this (instead of the static
	 * library) and calls functions normally; the loader fills each slot with the address
	 * resolved from the loaded .ndl. Only FUNC exports get thunks (data symbols would need
	 * dllimport-style indirection at the call site). */
	if (implib) {
		if (!sym)
			die("--implib: no symbol table");
		// `out` is a DIRECTORY: write ONE assembly file per exported symbol, so the Makefile
		// can archive them (ar) and the program linker pulls ONLY the members it references —
		// the program imports just the symbols it actually uses, not the whole library. A
		// FUNCTION member has a `name: jmp [__imp_name]` thunk + the IAT slot; a DATA member
		// (e.g. stdout/errno) has only the slot (the program reaches it through a dllimport
		// macro, see nx-dllimport.h). The slot lives in `.nxlib.<soname>` so the
		// program-building mknx tags the import with its source library (per-DLL namespace).
		const char** done = malloc(sizeof(char*) * nsym);
		int nDone = 0;
		char path[1024];
		for (int i = 0; i < nsym; i++) {
			int bind = ELF_ST_BIND(sym[i].st_info);
			if (bind != STB_GLOBAL && bind != STB_WEAK) continue;
			unsigned flags = symSecFlags(&sym[i]);
			if (!(flags & SHF_ALLOC)) continue;            /* defined, in a loaded section */
			int isFunc = (flags & SHF_EXECINSTR) != 0;     /* code -> thunk; data -> slot only */
			const char* nm = symstr + sym[i].st_name;
			if (!nm[0]) continue;
			int want = exportAll;
			for (int k = 0; !want && k < nWantExport; k++)
				if (!strcmp(nm, wantExport[k])) want = 1;
			if (!want) continue;
			int dup = 0;                                   /* skip repeated names */
			for (int k = 0; !dup && k < nDone; k++)
				if (!strcmp(nm, done[k])) dup = 1;
			if (dup) continue;
			done[nDone++] = nm;
			snprintf(path, sizeof path, "%s/%s.s", out, nm);
			FILE* o = fopen(path, "w");
			if (!o)
				die("--implib: cannot open output file");
			fprintf(o, "[BITS 32]\n");
			// Prefix identifiers with `$` so nasm treats them literally even when the name is
			// a reserved word (e.g. `times`, `abs`); the `$` is not part of the symbol.
			if (isFunc)
				fprintf(o, "section .text\nglobal $%s\n$%s: jmp [$__imp_%s]\n", nm, nm, nm);
			if (soname)
				fprintf(o, "section .nxlib.%s progbits alloc write align=4\n", soname);
			else
				fprintf(o, "section .data\n");
			fprintf(o, "global $__imp_%s\n$__imp_%s: dd 0\n", nm, nm);
			fclose(o);
		}
		free(done);
		return 0;
	}

	/* 2) Base relocations. On x86_64 the linker emits SHT_RELA (with addend); on i386 SHT_REL.
	 *    We record ONLY R_X86_64_64 / R_386_32 sites against a DEFINED (section-relative)
	 *    symbol — those hold a module address (8 bytes on x86_64, 4 on i386) that shifts with
	 *    the load base. R_X86_64_PC32 / R_386_PC32 is RIP-/PC-relative (position-independent)
	 *    and is never relocated. R_X86_64_32S appears in small-model non-PIC code and is NOT a
	 *    base-reloc, but its presence is exactly why the image MUST load in the low 2 GiB —
	 *    which our fixed base 0x800000 guarantees. A reloc against an undefined/weak symbol
	 *    (resolved to 0) or an ABSOLUTE symbol (a fixed constant) must NOT be delta-adjusted —
	 *    doing so would turn e.g. a NULL function pointer into `delta` and crash on first use. */
	Buf relocs = {0};
	unsigned relocCount = 0;
	for (int i = 0; i < g_nsh; i++) {
		Elf_Shdr* s = sh(i);
		int isRela = 0;
#if defined(NX_FORCE64)
		isRela = (s->sh_type == SHT_RELA_T);
#endif
		if (s->sh_type != SHT_REL && !isRela) continue;
		Elf_Shdr* tgt = sh(s->sh_info);
		if (!(tgt->sh_flags & SHF_ALLOC)) continue;
		Elf_Sym* rsym = (Elf_Sym*) (g_elf + sh(s->sh_link)->sh_offset);   // this rel's symtab
		unsigned char* rbase = g_elf + s->sh_offset;
		unsigned esz = isRela ? sizeof(Elf_Rel) : sizeof(Elf_Rel);
#if defined(NX_FORCE64)
		if (isRela) esz = sizeof(Elf_Rela);
#endif
		int n = (int) (s->sh_size / esz);
		for (int j = 0; j < n; j++) {
			uint64_t r_off, r_info;
#if defined(NX_FORCE64)
			if (isRela) { Elf_Rela* r = (Elf_Rela*) (rbase + (size_t) j * esz); r_off = r->r_offset; r_info = r->r_info; }
			else        { Elf_Rel*  r = (Elf_Rel*)  (rbase + (size_t) j * esz); r_off = r->r_offset; r_info = r->r_info; }
#else
			{ Elf_Rel* r = (Elf_Rel*) (rbase + (size_t) j * esz); r_off = r->r_offset; r_info = r->r_info; }
#endif
			if (ELF_R_TYPE(r_info) != R_ABS64) continue;            // only the absolute fixup
			if (r_off < loadBase || r_off >= bssStart) continue;
			uint16_t shndx = rsym[ELF_R_SYM(r_info)].st_shndx;
			if (shndx == SHN_UNDEF || shndx == SHN_ABS) continue;   // not a module address
			bu64(&relocs, r_off);                                   // nxaddr_t-wide reloc entry
			relocCount++;
		}
	}

	/* 3) Exports (.ndl): named global symbols. String pool collects names. */
	Buf strs = {0};
	bput(&strs, "", 1);   /* offset 0 = empty string */
	Buf exports = {0};
	unsigned exportCount = 0;
	if (isDll && sym) {
		for (int i = 0; i < nsym; i++) {
			int bind = ELF_ST_BIND(sym[i].st_info);
			if (bind != STB_GLOBAL && bind != STB_WEAK) continue;   /* weak: stdin/out/err */
			if (!(symSecFlags(&sym[i]) & SHF_ALLOC)) continue;   /* defined, in a loaded section */
			const char* nm = symstr + sym[i].st_name;
			if (!nm[0]) continue;
			int want = exportAll;
			for (int k = 0; !want && k < nWantExport; k++)
				if (!strcmp(nm, wantExport[k])) want = 1;
			if (!want) continue;
			unsigned nameOff = strs.len;
			bput(&strs, nm, strlen(nm) + 1);
			NxExport e = { nameOff, sym[i].st_value };   /* nameOff fixed up below */
			bput(&exports, &e, sizeof e);
			exportCount++;
		}
	}

	/* 4) Imports: every global symbol named "__imp_<name>" is an IAT slot the loader fills
	 *    with the address of import "<name>" (the import library provides the slot + a
	 *    jmp-thunk; see --implib). slotAddr = the slot's address; the name goes in the
	 *    string pool (nameOff fixed to an absolute vaddr below). */
	Buf imports = {0};
	unsigned importCount = 0;
	if (sym) {
		for (int i = 0; i < nsym; i++) {
			if (ELF_ST_BIND(sym[i].st_info) != STB_GLOBAL) continue;
			if (sym[i].st_shndx == 0) continue;
			const char* nm = symstr + sym[i].st_name;
			if (strncmp(nm, "__imp_", 6) != 0 || !nm[6]) continue;
			unsigned nameOff = strs.len;
			bput(&strs, nm + 6, strlen(nm + 6) + 1);
			/* Source library = the slot's section name ".nxlib.<lib>" (per-DLL namespace);
			 * a slot in any other section (e.g. .data) gets libOff 0 -> resolve flat. */
			unsigned libOff = 0;
			unsigned shndx = sym[i].st_shndx;
			if (shndx < (unsigned) g_nsh) {
				const char* sn = shname(sh(shndx));
				if (!strncmp(sn, ".nxlib.", 7) && sn[7]) {
					libOff = strs.len;
					bput(&strs, sn + 7, strlen(sn + 7) + 1);
					/* A symbol imported from this library means the module needs it at load;
					 * record it so `needed` is derived from the actual imports rather than relying
					 * on the caller to pass a matching --need (the section name is stable for the
					 * program's lifetime, so storing the pointer is safe). */
					addNeed(needs, &nNeeds, sn + 7);
				}
			}
			NxImport im = { nameOff, sym[i].st_value, libOff };   /* offsets fixed up below */
			bput(&imports, &im, sizeof im);
			importCount++;
		}
	}
	/* 4b) Auto-import (Windows/MinGW style): an absolute (R_386_32 / R_X86_64_64) site against
	 *     an UNDEFINED named symbol is a direct reference to imported DATA (stdout/errno/
	 *     _ctype_b/...). Emit it as an NxImport whose slot IS the reference site, so the loader
	 *     patches the site with the symbol's address at load — no dllimport shim needed in the
	 *     source. (Function calls are PC32/RIP-relative and resolved via the import-library
	 *     thunks, so they never reach here.) On x86_64 these come from SHT_RELA (with addend);
	 *     on i386 from SHT_REL — both handled. */
	int missingFns = 0;
	for (int i = 0; i < g_nsh; i++) {
		Elf_Shdr* s = sh(i);
		int isRela = 0;
#if defined(NX_FORCE64)
		isRela = (s->sh_type == SHT_RELA_T);
#endif
		if (s->sh_type != SHT_REL && !isRela) continue;
		Elf_Shdr* tgt = sh(s->sh_info);
		if (!(tgt->sh_flags & SHF_ALLOC)) continue;
		Elf_Sym* rsym = (Elf_Sym*) (g_elf + sh(s->sh_link)->sh_offset);
		const char* rstr = (const char*) (g_elf + sh(sh(s->sh_link)->sh_link)->sh_offset);
		unsigned char* rbase = g_elf + s->sh_offset;
		unsigned esz = sizeof(Elf_Rel);
#if defined(NX_FORCE64)
		if (isRela) esz = sizeof(Elf_Rela);
#endif
		int n = (int) (s->sh_size / esz);
		for (int j = 0; j < n; j++) {
			uint64_t r_off, r_info;
#if defined(NX_FORCE64)
			if (isRela) { Elf_Rela* r = (Elf_Rela*) (rbase + (size_t) j * esz); r_off = r->r_offset; r_info = r->r_info; }
			else        { Elf_Rel*  r = (Elf_Rel*)  (rbase + (size_t) j * esz); r_off = r->r_offset; r_info = r->r_info; }
#else
			{ Elf_Rel* r = (Elf_Rel*) (rbase + (size_t) j * esz); r_off = r->r_offset; r_info = r->r_info; }
#endif
			if (ELF_R_TYPE(r_info) != R_ABS64) continue;
			if (r_off < loadBase || r_off >= bssStart) continue;
			Elf_Sym* y = &rsym[ELF_R_SYM(r_info)];
			if (y->st_shndx != SHN_UNDEF) continue;          /* only unresolved (imported) symbols */
			/* Only STRONG undefined symbols are imports; a WEAK undefined data ref is an optional
			 * symbol meant to read 0 (leave it 0 — don't try to resolve it at load). */
			if (ELF_ST_BIND(y->st_info) != STB_GLOBAL) continue;
			const char* nm = rstr + y->st_name;
			if (!nm[0] || !strncmp(nm, "__imp_", 6)) continue;
			unsigned nameOff = strs.len;
			bput(&strs, nm, strlen(nm) + 1);
			NxImport im2 = { nameOff, r_off, 0 };            /* slot = the reloc site; flat resolve */
			bput(&imports, &im2, sizeof im2);
			importCount++;
		}
		/* Safety: a STRONG undefined symbol called via PC32 (R_386_PC32 / R_X86_64_PC32) is a
		 * genuinely MISSING function (not a data import). --unresolved-symbols=ignore-all let the
		 * link pass, so we catch it HERE and fail the build — otherwise it would crash at runtime
		 * calling address 0. (A WEAK undefined function is an optional ref meant to test 0, left
		 * alone.) */
		for (int j = 0; j < n; j++) {
			uint64_t r_info;
#if defined(NX_FORCE64)
			if (isRela) r_info = ((Elf_Rela*) (rbase + (size_t) j * esz))->r_info;
			else        r_info = ((Elf_Rel*)  (rbase + (size_t) j * esz))->r_info;
#else
			r_info = ((Elf_Rel*) (rbase + (size_t) j * esz))->r_info;
#endif
			if (ELF_R_TYPE(r_info) != R_PC32) continue;
			Elf_Sym* y = &rsym[ELF_R_SYM(r_info)];
			if (y->st_shndx != SHN_UNDEF) continue;
			if (ELF_ST_BIND(y->st_info) != STB_GLOBAL) continue;
			const char* nm = rstr + y->st_name;
			if (nm[0]) { fprintf(stderr, "mknx: error: undefined function '%s'\n", nm); missingFns++; }
		}
	}
	if (missingFns) die("undefined function(s) above — missing from libc.ndl or a needed library");

	Buf needed = {0};
	for (int i = 0; i < nNeeds; i++) {
		unsigned nameOff = strs.len;
		bput(&strs, needs[i], strlen(needs[i]) + 1);
		NxNeeded nd = { nameOff };
		bput(&needed, &nd, sizeof nd);
	}

	/* Lay the tables out in the file AFTER the load image (at vaddr bssStart onward); the
	 * loader reads them from the staged file before zeroing bss, so they need not be
	 * mapped at runtime. Table fields in the header are absolute vaddrs (loadBase + file
	 * offset). String offsets recorded above are relative to the string pool start; fix
	 * them to absolute vaddrs now. */
	nxaddr_t cur = bssStart;                 /* vaddr cursor for appended tables */
	nxaddr_t impAddr = cur; cur += imports.len;
	nxaddr_t expAddr = cur; cur += exports.len;
	nxaddr_t relAddr = cur; cur += relocs.len;
	nxaddr_t needAddr = cur; cur += needed.len;
	nxaddr_t strAddr = cur; cur += strs.len;

	/* Fix import/export/needed nameOff (string-pool-relative -> absolute vaddr); libOff 0
	 * stays 0 (flat-resolved import). */
	NxImport* im = (NxImport*) imports.p;
	for (unsigned i = 0; i < importCount; i++) {
		im[i].nameOff += strAddr;
		if (im[i].libOff) im[i].libOff += strAddr;
	}
	NxExport* ex = (NxExport*) exports.p;
	for (unsigned i = 0; i < exportCount; i++) ex[i].nameOff += strAddr;
	NxNeeded* nn = (NxNeeded*) needed.p;
	for (int i = 0; i < nNeeds; i++) nn[i].nameOff += strAddr;

	/* Header lives in the first bytes of the load image (the .nxheader placeholder). */
	NxHeader h;
	memset(&h, 0, sizeof h);
	h.magic = NX_MAGIC; h.version = NX_VERSION; h.flags = isDll ? NX_FLAG_DLL : 0;
	h.entry = g_eh->e_entry; h.loadBase = loadBase; h.imageSize = imageSize;
	h.bssStart = bssStart; h.bssEnd = bssEnd;
	h.importTable = importCount ? impAddr : 0; h.importCount = importCount;
	h.exportTable = exportCount ? expAddr : 0; h.exportCount = exportCount;
	h.relocTable = relocCount ? relAddr : 0;   h.relocCount = relocCount;
	h.neededTable = nNeeds ? needAddr : 0;     h.neededCount = nNeeds;
	if (imageSize < sizeof(NxHeader)) die("image smaller than header");
	memcpy(image, &h, sizeof h);

	/* Write: [image][imports][exports][relocs][needed][strings]. */
	FILE* o = fopen(out, "wb");
	if (!o) die("cannot open output");
	fwrite(image, 1, imageSize, o);
	fwrite(imports.p, 1, imports.len, o);
	fwrite(exports.p, 1, exports.len, o);
	fwrite(relocs.p, 1, relocs.len, o);
	fwrite(needed.p, 1, needed.len, o);
	fwrite(strs.p, 1, strs.len, o);
	fclose(o);
	return 0;
}
